### PR TITLE
updated ur hangman game !!!

### PR DESCRIPTION
**Pull request by kittyofheaven**
update 
-fix upside down illustration
-automatically add first letter
-add play again features
-add bye bye messages

ps : u can delete my comment on the script while u merge it okayy, that comments just for explanation :)

### CODE REVIEW

**Comment by CodeBunny09** [comment]
Thanks so much UwU, lemme check once and then, I'm gonna commit!

**Review by CodeBunny09 — APPROVED** [review]
It was gr8!!

**Comment by lizhy2010** [comment]
Are you shure yor are a noob?

**Comment by lizhy2010** [comment]
This code is hard for me!!!

**Comment by CodeBunny09** [comment]
I was... I just improved the code after I learned new things. I started this project with no intentions of making a CLI Hangman game. I was just playing with loops when this idea struck in my mind 😂😂

**Pull request merged**
